dist: trusty
sudo: required

language: c++
compiler: gcc

branches:
  only:
    - master

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y build-essential

install:
  - mkdir build && cd build
  - cmake ..
  - make
  - make test
  - sudo make install
