sudo: required
service: docker
language: generic

branches:
  only:
    - master

env:
  global:
    - DOCKER_CACHE_FILE=$HOME/docker/cache.tar.gz

cache:
  directories:
    - $HOME/docker

before_install:
  - if [ -f ${DOCKER_CACHE_FILE} ]; then gunzip -c ${DOCKER_CACHE_FILE} | docker load; fi

install:
  - docker build -t formula-test:latest --pull=true ${TRAVIS_BUILD_DIR}

script:
  - if [[ ${TRAVIS_BRANCH} == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then mkdir -p $(dirname ${DOCKER_CACHE_FILE}); docker save $(docker history -q formula-test:latest | grep -v '<missing>') | gzip > ${DOCKER_CACHE_FILE}; fi
